---
- name: Install Dependencies
  apt:
    name: "{{ item }}"
  loop:
    - swig
    - libsqlite3-dev
    - libi2c-dev
    - libusb-1.0-0-dev
    - libwxgtk3.0-gtk3-dev
    - freeglut3-dev
    - ninja-build
    - cmake
    - build-essential