---

- name: Install Dependencies
  apt:
    name: "{{ item }}"
  loop:
    - swig
    - libsqlite3-dev
    - libi2c-dev
    - libusb-1.0-0-dev
    - libwxgtk3.0-gtk3-dev
    - freeglut3-dev

- name: Git checkout
  git:
    repo: "https://github.com/myriadrf/LimeSuite.git"
    dest: "{{ install_dir }}/LimeSuite"
    version: master
    recursive: yes
    depth: 1

- name: Build
  shell: |
    set -e
    cd {{ install_dir }}/LimeSuite
    mkdir -p build
    cd build
    cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-latomic ../
    ninja install
    ldconfig
    echo "$(pwd)" >> {{ config_dir }}/build.dirs

- name: Install UDEV Rules
  shell: |
    set -e
    cd {{ install_dir }}/LimeSuite/udev-rules
    ./install.sh
    echo "/etc/udev/rules.d/64-limesuite.rules" >> {{ config_dir }}/udev.paths

- name: Git checkout gr-limesdr
  git:
    repo: "https://github.com/myriadrf/gr-limesdr.git"
    dest: "{{ install_dir }}/gr-limesdr"
    version: gr-3.8
    recursive: yes
    depth: 1

- name: Build gr-limesdr
  shell: |
    set -e
    cd {{ install_dir }}/gr-limesdr
    mkdir -p build
    cd build
    cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-latomic ../
    ninja install
    ldconfig
    echo "$(pwd)" >> {{ config_dir }}/build.dirs