---
- name: Git checkout
  git:
    repo: https://github.com/pothosware/SoapyRTLSDR.git
    dest: "{{ install_dir }}/SoapyRTLSDR"
    version: master
    recursive: yes
    depth: 1

- name: Build
  shell: |
    set -e
    cd {{ install_dir }}/SoapyRTLSDR
    mkdir -p build
    cd build
    cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=/etc/pisdr/optimizations.cmake \
          -DCMAKE_CXX_FLAGS=-latomic ../
    ninja install
    ldconfig
    echo "$(pwd)" >> {{ config_dir }}/build.dirs