---
- name: Install generic Linux kernel
  apt:
    name: linux-image-generic
    install_recommends: yes

- name: Install GRUB Bootloader
  apt:
    name: grub-efi-amd64

- name: Install GRUB System
  shell: |
    set -e
    grub-install --target=x86_64-efi
    sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*/& net.ifnames=0 biosdevname=0/' /etc/default/grub
    GRUB_DISABLE_OS_PROBER=true update-grub

- name: Install Linux firmware
  apt:
    name: "{{ item }}"
    install_recommends: yes
  loop:
    - linux-firmware