---

- name: Install Dependencies
  apt:
    name: "{{ item }}"
  loop:
    - swig
    - avahi-daemon
    - libavahi-client-dev
    - libusb-1.0-0-dev
    - python3-dev

- name: Git checkout SoapySDR
  git:
    repo: "https://github.com/pothosware/SoapySDR.git"
    dest: "{{ install_dir }}/SoapySDR"
    version: master
    recursive: yes
    depth: 1

- name: Build SoapySDR
  shell: |
    set -e
    cd {{ install_dir }}/SoapySDR
    mkdir -p build
    cd build
    cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=/etc/pisdr/optimizations.cmake ../
    ninja install
    ldconfig
    echo "$(pwd)" >> {{ config_dir }}/build.dirs

- name: Git checkout SoapySDR Remote
  git:
    repo: "https://github.com/pothosware/SoapyRemote.git"
    dest: "{{ install_dir }}/SoapyRemote"
    version: master
    recursive: yes
    depth: 1

- name: Build SoapySDR Remote
  shell: |
    set -e
    cd {{ install_dir }}/SoapyRemote
    mkdir -p build
    cd build
    cmake -GNinja -DCMAKE_BUILD_TYPE=Release ../
    ninja install
    ldconfig
    echo "$(pwd)" >> {{ config_dir }}/build.dirs

- name: Git checkout gr-soapy
  git:
    repo: "https://gitlab.com/librespacefoundation/gr-soapy.git"
    dest: "{{ install_dir }}/gr-soapy"
    version: master
    recursive: yes
    depth: 1

- name: Build gr-soapy
  shell: |
    set -e
    cd {{ install_dir }}/gr-soapy
    mkdir -p build
    cd build
    cmake -GNinja -DCMAKE_BUILD_TYPE=Release ../
    ninja install
    ldconfig
    echo "$(pwd)" >> {{ config_dir }}/build.dirs