---
- name: Git checkout
  git:
    repo: https://github.com/airspy/airspyone_host.git
    dest: "{{ install_dir }}/Airspy"
    version: master
    recursive: yes
    depth: 1

- name: Build
  shell: |
    set -e
    cd {{ install_dir }}/Airspy
    mkdir -p build
    cd build
    cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=/etc/pisdr/optimizations.cmake \
          -DINSTALL_UDEV_RULES=ON ../
    ninja install
    ldconfig
    echo "$(pwd)" >> {{ config_dir }}/build.dirs

- name: Install UDEV Rules
  shell: |
    echo "/etc/udev/rules.d/52-airspy.rules" >> {{ config_dir }}/udev.paths