---
- name: Install Dependencies
  apt:
    name: "{{ item }}"
  loop:
    - libboost-all-dev
    - swig
    - libzmq3-dev
    - libfftw3-dev
    - libgsl-dev
    - libsdl1.2-dev
    - libusb-1.0-0-dev
    - libasound2-dev
    - portaudio19-dev
    - libportaudio2
    - pulseaudio
    - libjack-dev
    - libgmp-dev
    - libsdl1.2-dev
    - liblog4cpp5-dev
    - libqwt-qt5-dev
    - libqt5opengl5-dev
    - python3-numpy
    - python3-mako
    - python3-sphinx
    - python3-lxml
    - python3-pyqt5
    - python3-yaml
    - python3-click
    - python3-click-plugins
    - python3-zmq
    - python3-scipy
    - python3-pip
    - python3-gi
    - python3-gi-cairo
    - gobject-introspection
    - gir1.2-gtk-3.0
    - ninja-build
    - cmake
    - build-essential