---
- name: Git checkout
  git:
    repo: "https://github.com/gnuradio/gnuradio.git"
    dest: "{{ install_dir }}/gnuradio"
    version: maint-3.8
    recursive: yes

- name: Build
  shell: |
    set -e
    cd {{ install_dir }}/gnuradio
    mkdir -p build
    cd build
    cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=/etc/pisdr/optimizations.cmake ../
    ninja install
    ldconfig
    echo "$(pwd)" >> {{ config_dir }}/build.dirs