---
- name: Mount pseudo filesystems
  connection: local
  shell: |
    ROOTFS_DIR={{ lookup('env', 'ANSIBLE_ROOTFS_DIR') }}

  	if grep -q "$(realpath "${ROOTFS_DIR}"/proc)"; then
      mount -t proc proc "${ROOTFS_DIR}/proc"
    fi

    if grep -q "$(realpath "${ROOTFS_DIR}"/dev)"; then
      mount --bind /dev "${ROOTFS_DIR}/dev"
    fi
    
    if grep -q "$(realpath "${ROOTFS_DIR}"/dev/pts)"; then
      mount --bind /dev/pts "${ROOTFS_DIR}/dev/pts"
    fi

    if grep -q "$(realpath "${ROOTFS_DIR}"/sys)"; then
      mount --bind /sys "${ROOTFS_DIR}/sys"
    fi