---
- name: Mount pseudo filesystems
  connection: local
  shell: |
    mount -o bind,ro /dev {{ lookup('env', 'ANSIBLE_ROOTFS_DIR') }}/dev
    mount -o bind,ro /dev/pts {{ lookup('env', 'ANSIBLE_ROOTFS_DIR') }}/dev/pts
    mount -t proc none {{ lookup('env', 'ANSIBLE_ROOTFS_DIR') }}/proc
    mount -t sysfs none {{ lookup('env', 'ANSIBLE_ROOTFS_DIR') }}/sys