---
- name: Install headless system
  hosts: pisdr
  connection: chroot
  pre_tasks:
    - include: tasks/mount.yaml
    - include: tasks/update-apt.yaml
  roles:
    - uhd
    - gnuradio
    - soapysdr
    - limesdr
    - airspy
    - airspyhf
    - rtlsdr
    - plutosdr
    - hackrf
  post_tasks:
    - include: tasks/umount.yaml
